### ISSUE TITLE
In this project,Does it support the chinese OCR detection?

### ISSUE THREAD

**Issue by gittigxuy** [BelBES/crnn-pytorch#1]

**Comment by BelBES** [comment]
Hi,

Currently there are not any pre-trained models available in public for this OCR. 
In my own experiments I worked with english alphabet only, and I don't know anything about of Chinese alphabet. But I think that you can try to train model for Chinese alphabet on your custom dataset (guide how to do it you can find in README.md).

Best regards

**Comment by gittigxuy** [comment]
have you finished your project?

**Comment by BelBES** [comment]
Nope, currently this project have status "Work in process".
