### ISSUE TITLE
Evaluation on CPU

### ISSUE THREAD

**Issue by cbasavaraj** [BelBES/crnn-pytorch#12]
Hi, I am getting poor performance when I test a trained model on CPU (but the checkpoint's working well on GPU as per validation numbers). Details here:
https://discuss.pytorch.org/t/different-results-on-cpu-and-gpu/22289/3
Appreciate any feedback, thanks.

**Comment by BelBES** [comment]
Hi, 
Did you check that all layers has been loaded from checkpoint? It's look like that some keys from snapshot not match with keys from network and some layers initialize with random weights on CPU.
