### ISSUE TITLE
how to create symbols_in_aphabet ? 

### ISSUE THREAD

**Issue by 10183308** [BelBES/crnn-pytorch#13]
Could you help me how to create symbols_in_aphabet ?

what is the symbols_in_aphabet format?

Could you give me some example?

thank you very much

**Comment by BelBES** [comment]
It's a simple string of symbols from alphabet, for exaplme "0123456789abc".
Position of symbol will interpret as a class id of symbol.

**Comment by 10183308** [comment]
@BelBES ok ,I see,thank you so much
