### ISSUE TITLE
Multiple lines images training

### ISSUE THREAD

**Issue by mit456** [BelBES/crnn-pytorch#4]
Hello,

Is it okay if I train the network on a dataset in which all images contains multiple lines of text at arbitrary positions? Here are some example images of my custom dataset
![business_powerpoint_templates_liner_flow_creative_text_boxes_diagram_sales_ppt_slides_slide01_1](https://user-images.githubusercontent.com/4567139/41296184-0402656c-6e7a-11e8-87cf-7dda7645077c.jpg)
![swot-pack-1-google-slides-template-powerpoint-download](https://user-images.githubusercontent.com/4567139/41296192-084d94a2-6e7a-11e8-9f35-2b42c40b92fd.jpg)
![30](https://user-images.githubusercontent.com/4567139/41296295-43183c04-6e7a-11e8-8e6f-9b0601a2f62b.png)

**Comment by BelBES** [comment]
Nope, this project only for recognition, not for detection

**Comment by mit456** [comment]
Thanks for your comment.
